/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Highlights = {
  _type: "highlights";
  title?: string;
  items?: Array<{
    icon?:
      | "arrow-down"
      | "arrow-right"
      | "arrow-up-right"
      | "bar-up"
      | "box"
      | "briefcase"
      | "calendar"
      | "cart"
      | "chart-bar"
      | "chart-line"
      | "chart"
      | "check"
      | "chevron-down"
      | "chevron-right"
      | "clock"
      | "close"
      | "cursor"
      | "document"
      | "external-link"
      | "facebook"
      | "globe"
      | "growth-arrow"
      | "handshake"
      | "image"
      | "instagram"
      | "lightbulb"
      | "lightning"
      | "link"
      | "linkedin"
      | "location-pin"
      | "location"
      | "mail"
      | "megaphone"
      | "menu"
      | "phone"
      | "pie-chart"
      | "plus"
      | "quote"
      | "rocket"
      | "search"
      | "send"
      | "shield-check"
      | "shield"
      | "star"
      | "tag"
      | "target"
      | "trophy"
      | "twitter-x"
      | "users";
    label?: string;
    _type: "highlight";
    _key: string;
  }>;
};

export type Checklist = {
  _type: "checklist";
  items?: Array<string>;
};

export type Callout = {
  _type: "callout";
  tone?: "tip" | "benefit";
  title?: string;
  text?: string;
};

export type Section = {
  _type: "section";
  title?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  category?: CategoryReference;
  author?: AuthorReference;
  publishedAt?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & Section)
    | ({
        _key: string;
      } & Callout)
    | ({
        _key: string;
      } & Checklist)
    | ({
        _key: string;
      } & Highlights)
  >;
  featured?: boolean;
  popularRank?: number;
  sectionNoun?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  role?: string;
  bio?: string;
  linkedin?: string;
  email?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Highlights
  | Checklist
  | Callout
  | Section
  | SanityImageAssetReference
  | CategoryReference
  | AuthorReference
  | Post
  | Author
  | SanityImageCrop
  | SanityImageHotspot
  | Category
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries.ts
// Variable: categoriesQuery
// Query: *[_type == "category"] | order(title asc) {    "slug": slug.current,    title  }
export type CategoriesQueryResult = Array<{
  slug: string | null;
  title: string | null;
}>;

// Source: src/sanity/queries.ts
// Variable: categoryCountsQuery
// Query: *[_type == "category"] | order(title asc) {    "slug": slug.current,    title,    "count": count(*[_type == "post" && references(^._id)])  }
export type CategoryCountsQueryResult = Array<{
  slug: string | null;
  title: string | null;
  count: number;
}>;

// Source: src/sanity/queries.ts
// Variable: allPostSlugsQuery
// Query: *[_type == "post" && defined(slug.current)].slug.current
export type AllPostSlugsQueryResult = Array<string | null>;

// Source: src/sanity/queries.ts
// Variable: featuredPostQuery
// Query: *[_type == "post" && featured == true] | order(publishedAt desc)[0] {      "slug": slug.current,  title,  excerpt,  "category": category->slug.current,  "categoryTitle": category->title,  "coverImage": coverImage.asset->url,  author->{    name,    "avatar": avatar.asset->url,    role,    bio,    linkedin,    email  },  publishedAt,  featured,  popularRank  }
export type FeaturedPostQueryResult = {
  slug: string | null;
  title: string | null;
  excerpt: string | null;
  category: string | null;
  categoryTitle: string | null;
  coverImage: string | null;
  author: {
    name: string | null;
    avatar: string | null;
    role: string | null;
    bio: string | null;
    linkedin: string | null;
    email: string | null;
  } | null;
  publishedAt: string | null;
  featured: true;
  popularRank: number | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: popularPostsQuery
// Query: *[_type == "post" && defined(popularRank)] | order(popularRank asc) {      "slug": slug.current,  title,  excerpt,  "category": category->slug.current,  "categoryTitle": category->title,  "coverImage": coverImage.asset->url,  author->{    name,    "avatar": avatar.asset->url,    role,    bio,    linkedin,    email  },  publishedAt,  featured,  popularRank  }
export type PopularPostsQueryResult = Array<{
  slug: string | null;
  title: string | null;
  excerpt: string | null;
  category: string | null;
  categoryTitle: string | null;
  coverImage: string | null;
  author: {
    name: string | null;
    avatar: string | null;
    role: string | null;
    bio: string | null;
    linkedin: string | null;
    email: string | null;
  } | null;
  publishedAt: string | null;
  featured: boolean | null;
  popularRank: number;
}>;

// Source: src/sanity/queries.ts
// Variable: archivePostsQuery
// Query: *[    _type == "post"    && featured != true    && ($category == "all" || category->slug.current == $category)    && (      $query == ""      || title match $query + "*"      || excerpt match $query + "*"    )  ] | order(publishedAt desc) {      "slug": slug.current,  title,  excerpt,  "category": category->slug.current,  "categoryTitle": category->title,  "coverImage": coverImage.asset->url,  author->{    name,    "avatar": avatar.asset->url,    role,    bio,    linkedin,    email  },  publishedAt,  featured,  popularRank  }
export type ArchivePostsQueryResult = Array<{
  slug: string | null;
  title: string | null;
  excerpt: string | null;
  category: string | null;
  categoryTitle: string | null;
  coverImage: string | null;
  author: {
    name: string | null;
    avatar: string | null;
    role: string | null;
    bio: string | null;
    linkedin: string | null;
    email: string | null;
  } | null;
  publishedAt: string | null;
  featured: boolean | null;
  popularRank: number | null;
}>;

// Source: src/sanity/queries.ts
// Variable: postBySlugQuery
// Query: *[_type == "post" && slug.current == $slug][0] {      "slug": slug.current,  title,  excerpt,  "category": category->slug.current,  "categoryTitle": category->title,  "coverImage": coverImage.asset->url,  author->{    name,    "avatar": avatar.asset->url,    role,    bio,    linkedin,    email  },  publishedAt,  featured,  popularRank,    "sectionNoun": coalesce(sectionNoun, "Sections"),      body[]{    ...,    "type": _type,    markDefs[]{...}  }  }
export type PostBySlugQueryResult = {
  slug: string | null;
  title: string | null;
  excerpt: string | null;
  category: string | null;
  categoryTitle: string | null;
  coverImage: string | null;
  author: {
    name: string | null;
    avatar: string | null;
    role: string | null;
    bio: string | null;
    linkedin: string | null;
    email: string | null;
  } | null;
  publishedAt: string | null;
  featured: boolean | null;
  popularRank: number | null;
  sectionNoun: string | "Sections";
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: never;
        markDefs: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }> | null;
        level?: number;
        _type: "block";
        _key: string;
        type: "block";
      }
    | {
        _key: string;
        _type: "callout";
        tone?: "benefit" | "tip";
        title?: string;
        text?: string;
        type: "callout";
        markDefs: null;
      }
    | {
        _key: string;
        _type: "checklist";
        items?: Array<string>;
        type: "checklist";
        markDefs: null;
      }
    | {
        _key: string;
        _type: "highlights";
        title?: string;
        items?: Array<{
          icon?:
            | "arrow-down"
            | "arrow-right"
            | "arrow-up-right"
            | "bar-up"
            | "box"
            | "briefcase"
            | "calendar"
            | "cart"
            | "chart-bar"
            | "chart-line"
            | "chart"
            | "check"
            | "chevron-down"
            | "chevron-right"
            | "clock"
            | "close"
            | "cursor"
            | "document"
            | "external-link"
            | "facebook"
            | "globe"
            | "growth-arrow"
            | "handshake"
            | "image"
            | "instagram"
            | "lightbulb"
            | "lightning"
            | "link"
            | "linkedin"
            | "location-pin"
            | "location"
            | "mail"
            | "megaphone"
            | "menu"
            | "phone"
            | "pie-chart"
            | "plus"
            | "quote"
            | "rocket"
            | "search"
            | "send"
            | "shield-check"
            | "shield"
            | "star"
            | "tag"
            | "target"
            | "trophy"
            | "twitter-x"
            | "users";
          label?: string;
          _type: "highlight";
          _key: string;
        }>;
        type: "highlights";
        markDefs: null;
      }
    | {
        _key: string;
        _type: "section";
        title?: string;
        type: "section";
        markDefs: null;
      }
  > | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: relatedPostsQuery
// Query: *[_type == "post" && slug.current != $slug]    | order(select(category->slug.current == $category => 0, 1) asc, publishedAt desc)    [0...$limit] {        "slug": slug.current,  title,  excerpt,  "category": category->slug.current,  "categoryTitle": category->title,  "coverImage": coverImage.asset->url,  author->{    name,    "avatar": avatar.asset->url,    role,    bio,    linkedin,    email  },  publishedAt,  featured,  popularRank    }
export type RelatedPostsQueryResult = Array<{
  slug: string | null;
  title: string | null;
  excerpt: string | null;
  category: string | null;
  categoryTitle: string | null;
  coverImage: string | null;
  author: {
    name: string | null;
    avatar: string | null;
    role: string | null;
    bio: string | null;
    linkedin: string | null;
    email: string | null;
  } | null;
  publishedAt: string | null;
  featured: boolean | null;
  popularRank: number | null;
}>;

// Source: src/sanity/queries.ts
// Variable: nextPostQuery
// Query: *[    _type == "post"    && (      publishedAt < $publishedAt      || (publishedAt == $publishedAt && slug.current > $slug)    )  ] | order(publishedAt desc, slug.current asc)[0] {      "slug": slug.current,  title,  excerpt,  "category": category->slug.current,  "categoryTitle": category->title,  "coverImage": coverImage.asset->url,  author->{    name,    "avatar": avatar.asset->url,    role,    bio,    linkedin,    email  },  publishedAt,  featured,  popularRank  }
export type NextPostQueryResult = {
  slug: string | null;
  title: string | null;
  excerpt: string | null;
  category: string | null;
  categoryTitle: string | null;
  coverImage: string | null;
  author: {
    name: string | null;
    avatar: string | null;
    role: string | null;
    bio: string | null;
    linkedin: string | null;
    email: string | null;
  } | null;
  publishedAt: string | null;
  featured: boolean | null;
  popularRank: number | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "category"] | order(title asc) {\n    "slug": slug.current,\n    title\n  }\n': CategoriesQueryResult;
    '\n  *[_type == "category"] | order(title asc) {\n    "slug": slug.current,\n    title,\n    "count": count(*[_type == "post" && references(^._id)])\n  }\n': CategoryCountsQueryResult;
    '\n  *[_type == "post" && defined(slug.current)].slug.current\n': AllPostSlugsQueryResult;
    '\n  *[_type == "post" && featured == true] | order(publishedAt desc)[0] {\n    \n  "slug": slug.current,\n  title,\n  excerpt,\n  "category": category->slug.current,\n  "categoryTitle": category->title,\n  "coverImage": coverImage.asset->url,\n  author->{\n    name,\n    "avatar": avatar.asset->url,\n    role,\n    bio,\n    linkedin,\n    email\n  },\n  publishedAt,\n  featured,\n  popularRank\n\n  }\n': FeaturedPostQueryResult;
    '\n  *[_type == "post" && defined(popularRank)] | order(popularRank asc) {\n    \n  "slug": slug.current,\n  title,\n  excerpt,\n  "category": category->slug.current,\n  "categoryTitle": category->title,\n  "coverImage": coverImage.asset->url,\n  author->{\n    name,\n    "avatar": avatar.asset->url,\n    role,\n    bio,\n    linkedin,\n    email\n  },\n  publishedAt,\n  featured,\n  popularRank\n\n  }\n': PopularPostsQueryResult;
    '\n  *[\n    _type == "post"\n    && featured != true\n    && ($category == "all" || category->slug.current == $category)\n    && (\n      $query == ""\n      || title match $query + "*"\n      || excerpt match $query + "*"\n    )\n  ] | order(publishedAt desc) {\n    \n  "slug": slug.current,\n  title,\n  excerpt,\n  "category": category->slug.current,\n  "categoryTitle": category->title,\n  "coverImage": coverImage.asset->url,\n  author->{\n    name,\n    "avatar": avatar.asset->url,\n    role,\n    bio,\n    linkedin,\n    email\n  },\n  publishedAt,\n  featured,\n  popularRank\n\n  }\n': ArchivePostsQueryResult;
    '\n  *[_type == "post" && slug.current == $slug][0] {\n    \n  "slug": slug.current,\n  title,\n  excerpt,\n  "category": category->slug.current,\n  "categoryTitle": category->title,\n  "coverImage": coverImage.asset->url,\n  author->{\n    name,\n    "avatar": avatar.asset->url,\n    role,\n    bio,\n    linkedin,\n    email\n  },\n  publishedAt,\n  featured,\n  popularRank\n,\n    "sectionNoun": coalesce(sectionNoun, "Sections"),\n    \n  body[]{\n    ...,\n    "type": _type,\n    markDefs[]{...}\n  }\n\n  }\n': PostBySlugQueryResult;
    '\n  *[_type == "post" && slug.current != $slug]\n    | order(select(category->slug.current == $category => 0, 1) asc, publishedAt desc)\n    [0...$limit] {\n      \n  "slug": slug.current,\n  title,\n  excerpt,\n  "category": category->slug.current,\n  "categoryTitle": category->title,\n  "coverImage": coverImage.asset->url,\n  author->{\n    name,\n    "avatar": avatar.asset->url,\n    role,\n    bio,\n    linkedin,\n    email\n  },\n  publishedAt,\n  featured,\n  popularRank\n\n    }\n': RelatedPostsQueryResult;
    '\n  *[\n    _type == "post"\n    && (\n      publishedAt < $publishedAt\n      || (publishedAt == $publishedAt && slug.current > $slug)\n    )\n  ] | order(publishedAt desc, slug.current asc)[0] {\n    \n  "slug": slug.current,\n  title,\n  excerpt,\n  "category": category->slug.current,\n  "categoryTitle": category->title,\n  "coverImage": coverImage.asset->url,\n  author->{\n    name,\n    "avatar": avatar.asset->url,\n    role,\n    bio,\n    linkedin,\n    email\n  },\n  publishedAt,\n  featured,\n  popularRank\n\n  }\n': NextPostQueryResult;
  }
}
